In [ ]:
import pandas as pd
import numpy  as np

In [ ]:
from google.colab import drive ; drive.mount("/content/drive")
df = pd.read_csv("/content/drive/My Drive/Dataset/TubesDSC/train.csv")
df.head()

Mounted at /content/drive


id_pasien jenis_kelamin  umur  ...   bmi         merokok stroke
0     100000     Laki-laki    43  ...  26.1  mantan perokok      0
1     100001     Perempuan    58  ...  21.2           tidak      0
2     100002     Laki-laki    29  ...  29.7           tidak      0
3     100003     Laki-laki    54  ...  27.7           tidak      0
4     100004     Laki-laki    78  ...  36.3  mantan perokok      0

[5 rows x 12 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28075 entries, 0 to 28074
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   id_pasien             28075 non-null  int64  
 1   jenis_kelamin         28075 non-null  object 
 2   umur                  28075 non-null  int64  
 3   hipertensi            28075 non-null  object 
 4   penyakit_jantung      28075 non-null  object 
 5   sudah_menikah         28075 non-null  object 
 6   jenis_pekerjaan       28075 non-null  object 
 7   jenis_tempat_tinggal  28075 non-null  object 
 8   rata2_level_glukosa   28075 non-null  float64
 9   bmi                   28075 non-null  float64
 10  merokok               28075 non-null  object 
 11  stroke                28075 non-null  int64  
dtypes: float64(2), int64(3), object(7)
memory usage: 2.6+ MB


In [ ]:
df.describe(include='all').T

count unique        top  ...     50%     75%     max
id_pasien             28075    NaN        NaN  ...  114037  121056  128074
jenis_kelamin         28075      2  Perempuan  ...     NaN     NaN     NaN
umur                  28075    NaN        NaN  ...      48      62      82
hipertensi            28075      2      tidak  ...     NaN     NaN     NaN
penyakit_jantung      28075      2      tidak  ...     NaN     NaN     NaN
sudah_menikah         28075      2      sudah  ...     NaN     NaN     NaN
jenis_pekerjaan       28075      4     swasta  ...     NaN     NaN     NaN
jenis_tempat_tinggal  28075      2  Perkotaan  ...     NaN     NaN     NaN
rata2_level_glukosa   28075    NaN        NaN  ...   92.14  113.85  291.05
bmi                   28075    NaN        NaN  ...    28.9    33.9      92
merokok               28075      3      tidak  ...     NaN     NaN     NaN
stroke                28075    NaN        NaN  ...       0       0       1

[12 rows x 11 columns]

In [ ]:
df.loc[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [id_pasien, jenis_kelamin, umur, hipertensi, penyakit_jantung, sudah_menikah, jenis_pekerjaan, jenis_tempat_tinggal, rata2_level_glukosa, bmi, merokok, stroke]
Index: []

In [ ]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [id_pasien, jenis_kelamin, umur, hipertensi, penyakit_jantung, sudah_menikah, jenis_pekerjaan, jenis_tempat_tinggal, rata2_level_glukosa, bmi, merokok, stroke]
Index: []

In [ ]:
df['stroke'].value_counts(normalize=True)

0    0.986358
1    0.013642
Name: stroke, dtype: float64

In [ ]:
test = pd.read_csv("/content/drive/My Drive/Dataset/TubesDSC/data_test.csv")
test.head()

id_pasien jenis_kelamin  umur  ... rata2_level_glukosa   bmi         merokok
0       2000     Laki-laki    24  ...               83.45  25.3           tidak
1       2001     Perempuan    81  ...              127.35  35.6  mantan perokok
2       2002     Laki-laki    41  ...               65.00  21.0   perokok aktif
3       2003     Laki-laki    30  ...               88.30  32.0           tidak
4       2004     Laki-laki    50  ...               63.15  25.1           tidak

[5 rows x 11 columns]

In [ ]:
df.isna().sum()

id_pasien               0
jenis_kelamin           0
umur                    0
hipertensi              0
penyakit_jantung        0
sudah_menikah           0
jenis_pekerjaan         0
jenis_tempat_tinggal    0
rata2_level_glukosa     0
bmi                     0
merokok                 0
stroke                  0
dtype: int64

In [ ]:
df = df[["jenis_kelamin","umur","hipertensi","penyakit_jantung","sudah_menikah","jenis_pekerjaan","jenis_tempat_tinggal","rata2_level_glukosa","bmi","merokok","stroke"]]
df.head()

jenis_kelamin  umur hipertensi  ...   bmi         merokok stroke
0     Laki-laki    43      tidak  ...  26.1  mantan perokok      0
1     Perempuan    58      tidak  ...  21.2           tidak      0
2     Laki-laki    29      tidak  ...  29.7           tidak      0
3     Laki-laki    54      tidak  ...  27.7           tidak      0
4     Laki-laki    78         ya  ...  36.3  mantan perokok      0

[5 rows x 11 columns]

In [ ]:
df["merokok"].unique()

array(['mantan perokok', 'tidak', 'perokok aktif'], dtype=object)

In [ ]:
df["hipertensi"] = df["hipertensi"].replace({"tidak":0,"ya":1})
df["penyakit_jantung"] = df["penyakit_jantung"].replace({"ya":1,"tidak":0})
df["sudah_menikah"] = df["sudah_menikah"].replace({"sudah":1,"belum":0})
test["hipertensi"] = test["hipertensi"].replace({"tidak":0,"ya":1})
test["penyakit_jantung"] = test["penyakit_jantung"].replace({"ya":1,"tidak":0})
test["sudah_menikah"] = test["sudah_menikah"].replace({"sudah":1,"belum":0})

In [ ]:
dummies = pd.get_dummies(df[["jenis_pekerjaan"]])
dummiesTest = pd.get_dummies(test[["jenis_pekerjaan"]])

In [ ]:
dummies = pd.get_dummies(df[["jenis_kelamin","jenis_pekerjaan","jenis_tempat_tinggal"]])
dummiesTest = pd.get_dummies(test[["jenis_kelamin","jenis_pekerjaan","jenis_tempat_tinggal"]])

In [ ]:
df[dummies.columns] = dummies
test[dummiesTest.columns] = dummiesTest
df.drop(["jenis_pekerjaan"],axis=1,inplace=True)
test.drop(["jenis_pekerjaan"],axis=1,inplace=True)

In [ ]:
df.head()

jenis_kelamin  ...  jenis_tempat_tinggal_Perkotaan
0     Laki-laki  ...                               0
1     Perempuan  ...                               0
2     Laki-laki  ...                               0
3     Laki-laki  ...                               1
4     Laki-laki  ...                               1

[5 rows x 18 columns]

In [ ]:
dummies = pd.get_dummies(df["merokok"],drop_first=True)
dummiesTest = pd.get_dummies(test["merokok"],drop_first=True)

In [ ]:
df[dummies.columns] = dummies
test[dummiesTest.columns] = dummiesTest

In [ ]:
df.drop("merokok",inplace=True,axis=1)
test.drop("merokok",inplace=True,axis=1)

In [ ]:
df.head()

jenis_kelamin  umur  ...  perokok aktif  tidak
0     Laki-laki    43  ...              0      0
1     Perempuan    58  ...              0      1
2     Laki-laki    29  ...              0      1
3     Laki-laki    54  ...              0      1
4     Laki-laki    78  ...              0      0

[5 rows x 19 columns]

In [ ]:
import tensorflow as tf
AUTO = tf.data.experimental.AUTOTUNE
import tensorflow_addons as tfa
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.models import Model
from tensorflow.keras import Input
from sklearn.preprocessing import MinMaxScaler

In [ ]:
StandardOBJ = MinMaxScaler()
StandardFit = StandardOBJ.fit_transform(df[["rata2_level_glukosa","bmi"]])
StandardFitTest = StandardOBJ.fit_transform(test[["rata2_level_glukosa","bmi"]])
StandardFit

array([[0.17530927, 0.1953602 ],
       [0.25021183, 0.13553114],
       [0.27092866, 0.23931624],
       ...,
       [0.02563125, 0.22100122],
       [0.22508897, 0.18315018],
       [0.05965091, 0.22710623]])

In [ ]:
df["rata2_level_glukosa"] = StandardFit[:,0]
df["bmi"] = StandardFit[:,1]
test["rata2_level_glukosa"] = StandardFitTest[:,0]
test["bmi"] = StandardFitTest[:,1]

In [ ]:
df.drop(["jenis_kelamin","jenis_tempat_tinggal"],axis=1,inplace=True)
test.drop(["jenis_kelamin","jenis_tempat_tinggal"],axis=1,inplace=True)

In [ ]:
dfcopy=df.copy()
dfcopy2 = df.copy()

In [ ]:
dfcopy = df[df["stroke"] == 1]
dfcopy2 = df[df["stroke"]==0][:390]
dfcopy2.head()

umur  hipertensi  ...  perokok aktif  tidak
0    43           0  ...              0      0
1    58           0  ...              0      1
2    29           0  ...              0      1
3    54           0  ...              0      1
4    78           1  ...              0      0

[5 rows x 17 columns]

In [ ]:
finaldf = pd.concat([dfcopy,dfcopy2],axis=0)
finaldf.shape

(773, 17)

In [ ]:
from tensorflow.keras.utils import to_categorical
X = finaldf.drop("stroke",axis=1)
Y = finaldf["stroke"]
Y = Y.astype("float64")
X.shape, Y.shape

((773, 16), (773,))

In [ ]:
X.head()

umur  hipertensi  ...  perokok aktif  tidak
27     45           1  ...              1      0
59     78           0  ...              0      1
246    68           1  ...              0      1
297    68           1  ...              1      0
311    38           0  ...              0      0

[5 rows x 16 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val = train_test_split(X,Y , test_size=0.05, random_state=5)
x_train.shape, y_train.shape

((734, 16), (734,))

In [ ]:
y_train

86       0.0
241      0.0
71       0.0
18777    1.0
3413     1.0
        ... 
6098     1.0
17       0.0
8586     1.0
323      0.0
15581    1.0
Name: stroke, Length: 734, dtype: float64

In [ ]:
TrainDataset = (tf.data.Dataset.from_tensor_slices((x_train,y_train)).batch(32).prefetch(AUTO))
ValDataset = (tf.data.Dataset.from_tensor_slices((x_val,y_val)).batch(32).cache().prefetch(AUTO))
TrainDataset.element_spec

(TensorSpec(shape=(None, 16), dtype=tf.float64, name=None),
 TensorSpec(shape=(None,), dtype=tf.float64, name=None))

In [ ]:
ValDataset.element_spec

(TensorSpec(shape=(None, 16), dtype=tf.float64, name=None),
 TensorSpec(shape=(None,), dtype=tf.float64, name=None))

In [ ]:
input = Input(shape=(16,),dtype=tf.float64)
layer = Dense(units=64 ,activation=tf.nn.leaky_relu)(input)
layer = Dropout(0.76)(layer)
layer = Dense(units=32,activation=tf.nn.leaky_relu)(layer)
layer = Dropout(0.4)(layer)
layer = Dense(units=32,activation=tf.nn.relu)(layer)
layer = Dense(16,activation=tf.nn.tanh)(layer)
layer = Dropout(0.5)(layer)
layer = Dense(1, activation=tf.nn.sigmoid)(layer)

METRICS = [
        tf.keras.metrics.TruePositives(name='tp'),
        tf.keras.metrics.FalsePositives(name='fp'),
        tf.keras.metrics.TrueNegatives(name='tn'),
        tf.keras.metrics.FalseNegatives(name='fn'), 
        tf.keras.metrics.BinaryAccuracy(name='accuracy'),
        tf.keras.metrics.Precision(name='precision'),
        tf.keras.metrics.Recall(name='recall'),
        tf.keras.metrics.AUC(name='auc'),
  ] 
model = Model(inputs=[input],outputs=layer)
model.compile(loss=tf.keras.losses.BinaryCrossentropy(),
              optimizer=tf.keras.optimizers.Adam(0.01),
              metrics=METRICS)
model.summary()


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Model: "functional_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 16)]              0         
_________________________________________________________________
dense (Dense)                (None, 64)                1088      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
________________________

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping
Early=EarlyStopping(patience=100,monitor="val_loss")

In [ ]:
import math
def create_learning_rate_scheduler(max_learn_rate=1e-2,
                                   end_learn_rate=1e-6,
                                   warmup_epoch_count=3,
                                   total_epoch_count=15):

    def lr_scheduler(epoch):
        if epoch < warmup_epoch_count:
            res = max_learn_rate
        else:
            res = max_learn_rate*math.exp(math.log(end_learn_rate/max_learn_rate)*(epoch-warmup_epoch_count+1)/(total_epoch_count-warmup_epoch_count+1))
        return float(res)
    learning_rate_scheduler = tf.keras.callbacks.LearningRateScheduler(lr_scheduler, verbose=1)

    return learning_rate_scheduler

In [ ]:
model.fit(TrainDataset,verbose=False,validation_data=ValDataset,epochs=1000,callbacks=[create_learning_rate_scheduler(0.001,0.0005,100,200),Early])


Epoch 00001: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00002: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00003: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00004: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00005: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00006: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00007: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00008: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00009: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00010: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00011: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00012: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00013: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00014: LearningRateScheduler reducing learning rate to 0.001.

Epoch 00015: LearningRateSchedule

In [ ]:
x_train

umur  hipertensi  ...  perokok aktif  tidak
86       38           0  ...              0      1
241      24           0  ...              0      1
71       49           0  ...              1      0
18777    64           1  ...              0      0
3413     56           0  ...              0      1
...     ...         ...  ...            ...    ...
6098     69           0  ...              0      1
17       48           0  ...              0      1
8586     68           1  ...              0      1
323      45           0  ...              0      0
15581    70           0  ...              1      0

[734 rows x 16 columns]

In [ ]:
answer = np.argmax(model.predict(test[test.columns[1:]]),axis=1)
test['stroke']=answer
answ=test[["id_pasien","stroke"]]
answ.head()

id_pasien  stroke
0       2000       0
1       2001       0
2       2002       0
3       2003       0
4       2004       0

In [ ]:
answer

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
test.drop("stroke",axis=1,inplace=True)

In [ ]:
answ.to_csv("submit.csv",index=False)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

RandomObj = RandomForestClassifier(n_estimators=1000,max_depth=7,random_state=5)
RandomObj.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=7, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=5, verbose=0,
                       warm_start=False)

In [ ]:
from sklearn.metrics import classification_report
y_pred = RandomObj.predict(x_val)
print(classification_report(y_val,y_pred))

              precision    recall  f1-score   support

         0.0       0.94      0.71      0.81        21
         1.0       0.74      0.94      0.83        18

    accuracy                           0.82        39
   macro avg       0.84      0.83      0.82        39
weighted avg       0.85      0.82      0.82        39



In [ ]:
Ans =RandomObj.predict(test[test.columns[1:]])

In [ ]:
Ans = Ans.astype("int")

In [ ]:
Answer = pd.DataFrame(test["id_pasien"])
Answer["stroke"] = Ans
Answer.to_csv("/content/drive/My Drive/Dataset/TubesDSC/submitML.csv",index=False)

In [ ]:
Answer

id_pasien  stroke
0         2000       0
1         2001       1
2         2002       0
3         2003       0
4         2004       1
..         ...     ...
985       2985       0
986       2986       1
987       2987       0
988       2988       0
989       2989       1

[990 rows x 2 columns]

In [ ]:
Ans

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,

In [ ]:
Ans

array([0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,

In [ ]:
# df['stroke']= df['stroke'].astype('int')

In [ ]:
# df.to_csv("/content/drive/My Drive/Dataset/TubesDSC/submitML.csv",index=False)